import type { Migration } from '../types/Migration.js';

export const V0_5_BASELINE_TABLES = [
  'agent_approval_queue',
  'agent_task_records',
  'anchors',
  'background_jobs',
  'belief_evidence',
  'beliefs',
  'branch_entries',
  'branch_links',
  'cognitive_edges',
  'cognitive_nodes',
  'compiled_events',
  'compiler_confidence_runs',
  'entities',
  'entity_alias_conflicts',
  'entity_aliases',
  'entity_attributes',
  'entity_instances',
  'entity_mentions',
  'entity_relations',
  'event_cluster_entries',
  'event_clusters',
  'fact_access_log',
  'fact_supersede_chain',
  'facts',
  'graph_signals',
  'ingestion_processed_records',
  'ingestion_source_cursors',
  'interaction_units',
  'memory_events',
  'meta_proposals',
  'neurons',
  'pending_bindings',
  'pending_entity_resolution',
  'plasticity_graph_edge_audit',
  'plasticity_graph_edges',
  'plasticity_proposal_review_decisions',
  'plasticity_proposals',
  'policy_executions',
  'policy_projection_state',
  'project_branches',
  'projection_observability_rollups',
  'projection_observability_samples',
  'reasoning_chains',
  'reasoning_steps',
  'runtime_projection_state',
  'runtime_states',
  'runtime_transitions',
  'sandbox_snapshots',
  'synapses',
  'task_branch_entries',
  'task_branches',
  'temporal_adjacency',
  'time_bucket_entries',
  'time_buckets',
  'topology_membership',
  'trace_events',
  'user_session_scopes',
  'user_sessions',
  'vector_projection_state'
] as const;

export const migration_0001: Migration = {
  version: '0001',
  description: 'v0.5 baseline schema snapshot',
  up(_db) {},
  down(_db) {}
};
